# Generated by Django 4.2.14 on 2024-08-15 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("objects", "0015_clothing_heavysword"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=255)),
                ("gender", models.CharField(blank=True, max_length=50)),
                ("hero_points", models.IntegerField(default=0)),
                ("traits", models.JSONField(default=dict)),
                ("skills", models.JSONField(default=dict)),
                ("perks", models.JSONField(default=list)),
                ("flesh_wounds", models.IntegerField(default=0)),
                ("dramatic_wounds", models.IntegerField(default=0)),
                ("nationality", models.CharField(blank=True, max_length=100)),
                ("is_sorcerer", models.BooleanField(default=False)),
                ("duelist_style", models.CharField(blank=True, max_length=100)),
                (
                    "db_object",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_sheet",
                        to="objects.objectdb",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
