# Generated by Django 4.2.14 on 2024-08-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character_sheet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactersheet",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="armor_soak_keep",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="dracheneisen_slots",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="eisen_bought",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="money",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="move_dice",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="sorcery_knacks",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="sorte_magic_effects",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="unconscious",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="xp",
            field=models.IntegerField(default=0),
        ),
    ]
