# Generated by Django 4.2.14 on 2024-08-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character_sheet", "0002_charactersheet_approved_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charactersheet",
            name="money",
            field=models.JSONField(default=dict),
        ),
    ]
