# Generated by Django 4.2.14 on 2024-08-16 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character_sheet", "0003_alter_charactersheet_money"),
    ]

    operations = [
        migrations.CreateModel(
            name="Knack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("value", models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name="charactersheet",
            name="money",
        ),
        migrations.RemoveField(
            model_name="charactersheet",
            name="traits",
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="brawn",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="finesse",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="money_doubloons",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="money_guilders",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="panache",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="resolve",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="wits",
            field=models.IntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name="charactersheet",
            name="skills",
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("knacks", models.ManyToManyField(to="character_sheet.knack")),
            ],
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="skills",
            field=models.ManyToManyField(to="character_sheet.skill"),
        ),
    ]
