# Generated by Django 4.2.14 on 2024-08-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "character_sheet",
            "0005_sorceryknack_remove_charactersheet_sorcery_knacks_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="charactersheet",
            name="sorcery_knacks",
        ),
        migrations.DeleteModel(
            name="SorceryKnack",
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="sorcery_knacks",
            field=models.JSONField(default=dict),
        ),
    ]
