# Generated by Django 4.2.14 on 2024-08-16 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("character_sheet", "0006_remove_charactersheet_sorcery_knacks_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="skill",
            unique_together={("name", "category")},
        ),
    ]
