# Generated by Django 4.2.14 on 2024-08-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character_sheet", "0007_alter_skill_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knack",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
