# Generated by Django 4.2.14 on 2024-08-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character_sheet", "0008_alter_knack_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SorceryKnack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("value", models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name="charactersheet",
            name="sorcery_knacks",
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="sorcery_knacks",
            field=models.ManyToManyField(blank=True, to="character_sheet.sorceryknack"),
        ),
    ]
