# Generated by Django 4.2.14 on 2024-08-17 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "character_sheet",
            "0009_sorceryknack_remove_charactersheet_sorcery_knacks_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SwordsmanKnack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("value", models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="swordsman_knacks",
            field=models.ManyToManyField(
                blank=True, to="character_sheet.swordsmanknack"
            ),
        ),
    ]
