# Generated by Django 4.2.14 on 2024-08-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character_sheet", "0010_swordsmanknack_charactersheet_swordsman_knacks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charactersheet",
            name="dracheneisen_slots",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="charactersheet",
            name="sorte_magic_effects",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cups_boost", "Cups (Boost)"),
                    ("cups_curse", "Cups (Curse)"),
                    ("swords_boost", "Swords (Boost)"),
                    ("swords_curse", "Swords (Curse)"),
                    ("staves", "Staves"),
                    ("coins", "Coins"),
                    ("arcana", "Arcana"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
