# Generated by Django 4.2.14 on 2024-08-18 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character_sheet", "0011_alter_charactersheet_dracheneisen_slots_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactersheet",
            name="total_xp_accrued",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
