# Generated by Django 4.2.14 on 2024-08-19 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("character_sheet", "0012_charactersheet_total_xp_accrued"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="knacks",
        ),
        migrations.AddField(
            model_name="knack",
            name="skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="knacks",
                to="character_sheet.skill",
            ),
        ),
        migrations.AlterField(
            model_name="knack",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="knack",
            unique_together={("name", "skill")},
        ),
        migrations.CreateModel(
            name="SwordsmanSchool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "knacks",
                    models.ManyToManyField(
                        related_name="swordsman_schools", to="character_sheet.knack"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sorcery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "knacks",
                    models.ManyToManyField(
                        related_name="sorceries", to="character_sheet.knack"
                    ),
                ),
            ],
        ),
    ]
