# Generated by Django 4.2.14 on 2024-08-19 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("character_sheet", "0015_charactersheet_sorcery_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="charactersheet",
            name="sorcery_knacks",
        ),
        migrations.RemoveField(
            model_name="charactersheet",
            name="swordsman_knacks",
        ),
        migrations.DeleteModel(
            name="SorceryKnack",
        ),
        migrations.DeleteModel(
            name="SwordsmanKnack",
        ),
    ]
