# Generated by Django 4.2.14 on 2024-08-19 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("character_sheet", "0020_auto_20240819_0349"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="charactersheet",
            name="sorcery",
        ),
        migrations.RemoveField(
            model_name="charactersheet",
            name="swordsman_school",
        ),
        migrations.RemoveField(
            model_name="knack",
            name="value",
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="biography",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="personality",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="sorceries",
            field=models.ManyToManyField(
                blank=True,
                related_name="character_sheets",
                to="character_sheet.sorcery",
            ),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="swordsman_schools",
            field=models.ManyToManyField(
                blank=True,
                related_name="character_sheets",
                to="character_sheet.swordsmanschool",
            ),
        ),
        migrations.AlterField(
            model_name="charactersheet",
            name="skills",
            field=models.ManyToManyField(
                blank=True, related_name="character_sheets", to="character_sheet.skill"
            ),
        ),
        migrations.CreateModel(
            name="KnackValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField(default=0)),
                (
                    "character_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knack_values",
                        to="character_sheet.charactersheet",
                    ),
                ),
                (
                    "knack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knack_values",
                        to="character_sheet.knack",
                    ),
                ),
            ],
            options={
                "unique_together": {("character_sheet", "knack")},
            },
        ),
    ]
