# Generated by Django 4.2.14 on 2024-08-19 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("character_sheet", "0022_auto_20240819_0355"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knack",
            name="skill",
            field=models.ForeignKey(
                default="152",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="knacks",
                to="character_sheet.skill",
            ),
            preserve_default=False,
        ),
    ]
