# Generated by Django 4.2.14 on 2024-08-20 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("character_sheet", "0023_alter_knack_skill"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advantage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("cost", models.JSONField(default=list)),
                ("eisen_cost", models.IntegerField(blank=True, null=True)),
                ("bonus", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="charactersheet",
            name="perks",
        ),
        migrations.CreateModel(
            name="CharacterAdvantage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField(default=1)),
                (
                    "advantage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character_sheet.advantage",
                    ),
                ),
                (
                    "character_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_advantages",
                        to="character_sheet.charactersheet",
                    ),
                ),
            ],
            options={
                "unique_together": {("character_sheet", "advantage")},
            },
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="advantages",
            field=models.ManyToManyField(
                blank=True,
                related_name="character_sheets",
                through="character_sheet.CharacterAdvantage",
                to="character_sheet.advantage",
            ),
        ),
    ]
