# Generated by Django 4.2.14 on 2024-08-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character_sheet", "0024_advantage_remove_charactersheet_perks_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advantage",
            name="eisen_cost",
        ),
        migrations.AlterField(
            model_name="advantage",
            name="cost",
            field=models.JSONField(default=dict),
        ),
    ]
