# Generated by Django 4.2.14 on 2024-08-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character_sheet", "0027_swordsmanschool_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactersheet",
            name="special_effects",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
