# Generated by Django 4.2.14 on 2024-08-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character_sheet", "0029_alter_charactersheet_dramatic_wounds_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactersheet",
            name="reputation",
            field=models.IntegerField(default=5),
        ),
    ]
