# Generated by Django 4.2.14 on 2024-09-01 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Nation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("population", models.PositiveIntegerField(default=1000)),
                ("capital", models.CharField(blank=True, max_length=100)),
                ("important_cities", models.JSONField(blank=True, default=list)),
                ("government_type", models.CharField(blank=True, max_length=100)),
                ("ruler", models.CharField(blank=True, max_length=100)),
                ("currency", models.CharField(blank=True, max_length=50)),
                ("major_exports", models.JSONField(blank=True, default=list)),
                ("major_imports", models.JSONField(blank=True, default=list)),
                ("recent_history", models.TextField(blank=True)),
                ("notable_npcs", models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name="Stronghold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("location", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("ruler", models.CharField(blank=True, max_length=100)),
                (
                    "nation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strongholds",
                        to="nations.nation",
                    ),
                ),
            ],
        ),
    ]
