# Generated by Django 4.2.14 on 2024-08-17 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scripts", "0017_scriptbase_defaultscript_botstarter_combatscript_and_more"),
        ("banking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HoldingIncomeScriptProxy",
            fields=[],
            options={
                "verbose_name": "Holding Income Script",
                "verbose_name_plural": "Holding Income Scripts",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("scripts.scriptdb",),
        ),
    ]
