# Generated by Django 4.2.14 on 2024-08-23 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0015_clothing_heavysword"),
        ("crafts", "0002_alter_weaponmodel_evennia_object"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weaponmodel",
            name="evennia_object",
            field=models.OneToOneField(
                limit_choices_to={
                    "db_typeclass_path__endswith": "typeclasses.objects.Weapon"
                },
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weapon_model",
                to="objects.objectdb",
            ),
        ),
    ]
