# Generated by Django 4.2.14 on 2024-08-23 20:53

from django.db import migrations, models
import django.db.models.deletion
import world.crafts.utils


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0017_delete_aldanablade_delete_exit_delete_flamingsword_and_more"),
        ("crafts", "0004_alter_weaponmodel_evennia_object"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weaponmodel",
            name="evennia_object",
            field=models.OneToOneField(
                blank=True,
                limit_choices_to=world.crafts.utils.get_weapon_objects,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weapon_model",
                to="objects.objectdb",
            ),
        ),
    ]
