# Generated by Django 4.2.14 on 2024-08-24 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0018_delete_aldanablade_delete_flamingsword_and_more"),
        ("crafts", "0005_alter_weaponmodel_evennia_object"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weaponmodel",
            name="evennia_object",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weapon_model",
                to="objects.objectdb",
            ),
        ),
        migrations.AlterField(
            model_name="weaponmodel",
            name="parry_skill",
            field=models.CharField(
                blank=True,
                choices=[
                    ("parry (fencing)", "Parry (Fencing)"),
                    ("parry (knife)", "Parry (Knife)"),
                    ("parry (heavy weapon)", "Parry (Heavy Weapon)"),
                    ("parry (improvised weapon)", "Parry (Improvised Weapon)"),
                    ("parry (polearms)", "Parry (Polearms)"),
                    ("footwork", "Footwork"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
