# Generated by Django 4.2.14 on 2024-08-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crafts", "0006_alter_weaponmodel_evennia_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CraftingMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("value", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
