# Generated by Django 4.2.14 on 2024-08-24 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("character_sheet", "0030_charactersheet_reputation"),
        ("crafts", "0008_craftingrecipe_reciperequirement"),
    ]

    operations = [
        migrations.AddField(
            model_name="weaponmodel",
            name="crafted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="character_sheet.charactersheet",
            ),
        ),
        migrations.AddField(
            model_name="weaponmodel",
            name="material",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="crafts.craftingmaterial",
            ),
        ),
        migrations.AddField(
            model_name="weaponmodel",
            name="quality_level",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
