# Generated by Django 4.2.14 on 2024-08-25 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0018_delete_aldanablade_delete_flamingsword_and_more"),
        ("crafts", "0009_weaponmodel_crafted_by_weaponmodel_material_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Armor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=125)),
                ("armor", models.PositiveIntegerField(default=0)),
                ("soak_keep", models.PositiveIntegerField(default=1)),
                ("description", models.TextField(blank=True, max_length=300)),
                (
                    "armor_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("clothing", "Clothing"),
                            ("cuirass", "Cuirass"),
                            ("dracheneisen", "Dracheneisen"),
                            ("reinforced_clothing", "Reinforced Clothing"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("wear_location", models.JSONField(blank=True, default=list)),
                ("traits", models.JSONField(blank=True, default=dict)),
                ("cost", models.PositiveIntegerField(default=0)),
                (
                    "evennia_object",
                    models.OneToOneField(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="armor_model",
                        to="objects.objectdb",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
