# Generated by Django 4.2.14 on 2024-08-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crafts", "0010_armor"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeaponAbility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="WeaponModification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("damage_modifier", models.IntegerField(default=0)),
                ("roll_keep_modifier", models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="weaponmodel",
            name="abilities",
            field=models.ManyToManyField(blank=True, to="crafts.weaponability"),
        ),
        migrations.AddField(
            model_name="weaponmodel",
            name="modifications",
            field=models.ManyToManyField(blank=True, to="crafts.weaponmodification"),
        ),
    ]
