# Generated by Django 4.2.14 on 2024-08-25 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crafts", "0011_weaponability_weaponmodification_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weaponmodel",
            name="weight",
        ),
    ]
