# Generated by Django 4.2.14 on 2024-08-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0015_clothing_heavysword"),
        ("adventuring_guilds", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adventuringguild",
            options={
                "verbose_name": "Adventuring Guild",
                "verbose_name_plural": "Adventuring Guilds",
            },
        ),
        migrations.RenameField(
            model_name="adventuringguild",
            old_name="founder",
            new_name="db_founder",
        ),
        migrations.RenameField(
            model_name="adventuringguild",
            old_name="founding_date",
            new_name="db_founding_date",
        ),
        migrations.RenameField(
            model_name="adventuringguild",
            old_name="history",
            new_name="db_history",
        ),
        migrations.RenameField(
            model_name="adventuringguild",
            old_name="name",
            new_name="db_name",
        ),
        migrations.RenameField(
            model_name="adventuringguild",
            old_name="recent_history",
            new_name="db_recent_history",
        ),
        migrations.RemoveField(
            model_name="adventuringguild",
            name="Members",
        ),
        migrations.AddField(
            model_name="adventuringguild",
            name="db_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="adventuringguild",
            name="db_members",
            field=models.ManyToManyField(to="objects.objectdb"),
        ),
    ]
