# Generated by Django 4.2.14 on 2024-08-17 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0015_clothing_heavysword"),
        ("adventuring_guilds", "0002_alter_adventuringguild_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adventuringguild",
            name="db_founder",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    ("db_typeclass_path__contains", "typeclasses.characters")
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="founded_guilds",
                to="objects.objectdb",
            ),
        ),
        migrations.AlterField(
            model_name="adventuringguild",
            name="db_members",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to=models.Q(
                    ("db_typeclass_path__contains", "typeclasses.characters")
                ),
                related_name="adventuring_guilds",
                to="objects.objectdb",
            ),
        ),
    ]
