# Generated by Django 4.2.14 on 2024-08-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adventuring_guilds", "0003_alter_adventuringguild_db_founder_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adventuringguild",
            name="db_founder",
            field=models.CharField(default="", max_length=100),
        ),
    ]
