# Generated by Django 4.2.14 on 2024-08-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adventuring_guilds", "0007_alter_adventuringguild_db_holdings"),
    ]

    operations = [
        migrations.CreateModel(
            name="HoldingData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("holding_id", models.IntegerField(unique=True)),
                ("level", models.IntegerField(default=1)),
                ("total_income_generated", models.IntegerField(default=0)),
                ("last_upgrade_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
