# Generated by Django 4.2.14 on 2024-08-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0015_clothing_heavysword"),
        ("adventuring_guilds", "0009_alter_adventuringguild_db_holdings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adventuringguild",
            name="db_holdings",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to=models.Q(
                    ("db_typeclass_path__contains", "typeclasses.holdings.Holding")
                ),
                related_name="owned_by_guild",
                to="objects.objectdb",
            ),
        ),
    ]
