# Generated by Django 4.2.14 on 2024-08-17 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("adventuring_guilds", "0010_alter_adventuringguild_db_holdings"),
    ]

    operations = [
        migrations.CreateModel(
            name="Holding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "custom_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("holding_type", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                ("custom_description", models.TextField(blank=True)),
                ("level", models.IntegerField(default=1)),
                (
                    "income_type",
                    models.CharField(
                        choices=[("guilders", "Guilders"), ("doubloons", "Doubloons")],
                        max_length=20,
                    ),
                ),
                ("base_income", models.IntegerField(default=0)),
                ("upgrade_cost", models.IntegerField(default=0)),
                ("upgrade_multiplier", models.FloatField(default=1.5)),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("staff", models.JSONField(default=list)),
                ("events", models.JSONField(default=list)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="HoldingData",
        ),
        migrations.RemoveField(
            model_name="adventuringguild",
            name="db_holdings",
        ),
        migrations.AddField(
            model_name="holding",
            name="owning_guild",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="holdings",
                to="adventuring_guilds.adventuringguild",
            ),
        ),
    ]
