# Generated by Django 4.2.14 on 2024-08-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adventuring_guilds", "0011_holding_delete_holdingdata_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holding",
            name="holding_type",
            field=models.CharField(
                choices=[
                    ("tavern", "Tavern"),
                    ("workshop", "Craftsman's Workshop"),
                    ("farm", "Fertile Farm"),
                    ("mine", "Rich Mine"),
                ],
                max_length=50,
            ),
        ),
    ]
