# Generated by Django 4.2.14 on 2024-08-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0015_clothing_heavysword"),
        ("adventuring_guilds", "0012_alter_holding_holding_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="holding",
            name="staff",
        ),
        migrations.AddField(
            model_name="holding",
            name="staff",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={
                    "db_typeclass_path": "typeclasses.characters.Character"
                },
                related_name="staffed_holdings",
                to="objects.objectdb",
            ),
        ),
    ]
