# Generated by Django 4.2.14 on 2024-08-22 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adventuring_guilds", "0013_remove_holding_staff_holding_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holding",
            name="holding_type",
            field=models.CharField(
                choices=[
                    ("tavern", "Tavern"),
                    ("workshop", "Craftsman's Workshop"),
                    ("farm", "Fertile Farm"),
                    ("mine", "Rich Mine"),
                    ("swordsman academy", "Swordsman's Guild Academy"),
                ],
                max_length=50,
            ),
        ),
    ]
