# Generated by Django 4.2.14 on 2024-08-17 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("objects", "0015_clothing_heavysword"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("brawn", models.IntegerField(default=0)),
                ("finesse", models.IntegerField(default=0)),
                ("resolve", models.IntegerField(default=0)),
                ("wits", models.IntegerField(default=0)),
                ("panache", models.IntegerField(default=0)),
                ("cargo", models.IntegerField(default=0)),
                ("draft", models.IntegerField(default=0)),
                (
                    "captain",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="captained_ships",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "evennia_object",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ship",
                        to="objects.objectdb",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Modification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "ship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modifications",
                        to="ships.ship",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Flaw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "ship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flaws",
                        to="ships.ship",
                    ),
                ),
            ],
        ),
    ]
