# Generated by Django 4.2.14 on 2024-08-17 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0015_clothing_heavysword"),
        ("ships", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ship",
            name="evennia_object",
            field=models.OneToOneField(
                limit_choices_to={
                    "db_typeclass_path": "typeclasses.domain.ships.Ships"
                },
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ship",
                to="objects.objectdb",
            ),
        ),
    ]
