# Generated by Django 4.2.14 on 2024-08-27 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0018_delete_aldanablade_delete_flamingsword_and_more"),
        ("ships", "0002_alter_ship_evennia_object"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ship",
            name="evennia_object",
            field=models.OneToOneField(
                limit_choices_to={"db_typeclass_path": "typeclasses.domain.ships.Ship"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ship",
                to="objects.objectdb",
            ),
        ),
    ]
